targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
          - web/components/alg-iron-checked-element-behavior/main.dart
        options:
          compiler: dart2js
          dart2js_args:
            - --no-frequency-based-minification
