name: dart_alg_components
description: alg components for dart
version: 0.0.2
homepage: https://github.com/AdalbertoLacruz/dart_alg_components
author: Adalberto Lacruz <adalberto.lacruz@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.3
  test: '>=0.12.20+2 <0.13.0'

#web:
#  compiler:
#    debug: dartdevc

transformers:
  - dart_to_js_script_rewriter

  - test/pub_serve:
      $include: test/**_test.dart
