name: dart_alg_components
description: alg components for dart
version: 0.0.1
homepage: https://github.com/AdalbertoLacruz/dart_alg_components
author: Adalberto Lacruz <adalberto.lacruz@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  initialize: '>=0.6.0 <1.0.0'

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

#web:
#  compiler:
#    debug: dartdevc

transformers:
- initialize:
    entry_points: [
      'web/index.html',
      'web/components/iron-flex-layout/index.html'
      ]
- dart_to_js_script_rewriter
