name: dart_alg_components
description: alg components for dart
version: 0.0.9
homepage: https://github.com/AdalbertoLacruz/dart_alg_components
author: Adalberto Lacruz <adalberto.lacruz@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dev_dependencies:
  build_runner: ^0.8.8
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: '>=0.12.30 <0.13.0'

# Commands:
# > webdev serve
