name: dart_alg_components
description: alg components for dart
version: 0.0.7
homepage: https://github.com/AdalbertoLacruz/dart_alg_components
author: Adalberto Lacruz <adalberto.lacruz@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dev_dependencies:
  build_runner: ^0.8.1
  build_test: ^0.10.1
  build_web_compilers: ^0.3.5

  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.3

  test: '>=0.12.30 <0.13.0'

#web:
#  compiler:
#    debug: dartdevc

transformers:
  - dart_to_js_script_rewriter

  - test/pub_serve:
      $include: test/**_test.dart

# Commands:
# > pub run build_runner serve
